### ISSUE TITLE
Update templates - object keys instead of the array indexes

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver.org#105]
The new en.json has been added to Transifex. Translations had to be manually added (shout-out to @britttttk for handling that)

The following languages are 100% translated.
![Screenshot 2020-04-20 at 08 56 02](https://user-images.githubusercontent.com/36959754/79722713-d7a09080-82e4-11ea-9e33-3343e1ca5f20.png)

I think we should only add 100% translated languages. If we start adding partially completed ones like the current site shows, it is unclear where we can draw the line of translation being ready for the website, so I suggest we just do 100% = we add it.

**Comment by RiccardoMasutti** [comment]
I agree with 100% translated only

**Comment by britttttk** [comment]
I would go with a bit lower minimum like 80%, since sometimes translators don't translate strings if they think the English version is sufficient. Also that way if we add a few strings it will not drop the entire language until they update, but 100% makes sense too.

**Comment by pavlenex** [comment]
It's kinda tricky to draw a line. I believe this languages are added manually anyways, so when you **add** a 100% complete language and we add a certain new string, it won't drop, but what we have right now is slightly messy.

One more argument for 100% would be that people won't be motivated to complete a translations if it's already published.

I would add only 100% right now and if a new string appears they shouldn't be dropped.

**Comment by britttttk** [comment]
>I believe this languages are added manually anyways

hmm we should document this process to discuss if there is a better way. 

This is not particularly clear: https://github.com/btcpayserver/btcpayserver.org/blob/master/source/README.md#transifex-master

In the main repo there is a test (run locally) that pulls the translations using the transifex client when you run the test. It is possible to provide a minimum translation pull policy flag when using the client. I don't know exactly how it is happening here. 

ACK on 100%

**Comment by pavlenex** [comment]
Honestly I've no idea how we handle it, I've just suggested the way most projects I contributed to in the past such as bitcoin.org handles it.

I guess we can add a new language when it's 100% but allow it to drop up to 80-90% afterwards when new string is added. Would be good to have some sort of alert when it drops though so we can ping translators. But this is again me over-thinking us we add new strings every few months so it can be handled manually anyway.

Pinging @vswee to help us figure stuff out.

**Comment by vswee** [comment]
As far as I can recall:
Translators can opt-in to be notified when new strings require translating for a language they're subscribed to.

We always used 80% minimum threshold since the first switch to multilingual.
This worked because we never modified/added more than 1/5 strings.

Part of the build process involves pulling the stats from transifex on completeness so actions can be modified at that point.

100% is ideal so you'll hear no argument from me. There will be periods when the build process will drop languages though -remedied, as you said, by dropping min when new strings added.

**Comment by pavlenex** [comment]
Thanks for clarifying that @vswee gives a different perspective for me.

> We always used 80% minimum threshold since the first switch to multilingual.

How about we keep it then around 80-90% then? I assume that's the golden middle where the website won't look bad and we'll avoid websites being dropped out when we add a smaller change? Bear in mind that content changes will be kept at a minimum like we did so far.

@britttttk @vswee @dennisreimann @RiccardoMasutti  What do you guys think now thaw we have a whole perspective?

**Comment by dennisreimann** [comment]
I'm fine with 80-90%, sounds reasonable. 👍

**Comment by RiccardoMasutti** [comment]
> Thanks for clarifying that @vswee gives a different perspective for me.
> 
> > We always used 80% minimum threshold since the first switch to multilingual.
> 
> How about we keep it then around 80-90% then? I assume that's the golden middle where the website won't look bad and we'll avoid websites being dropped out when we add a smaller change? Bear in mind that content changes will be kept at a minimum like we did so far.
> 
> @britttttk @vswee @dennisreimann @RiccardoMasutti What do you guys think now thaw we have a whole perspective?

Nack for me. We should go for 100% imo

**Comment by dennisreimann** [comment]
> Nack for me. We should go for 100% imo

I think it makes sense to have some tolerance for the case that new strings get added. Otherwise the languages that don't get translated instantly would get removed, even though they might just miss one or two new strings.
