### ISSUE TITLE
Images Not Loading

### ISSUE THREAD

**Issue by Chibuikekenneth** [btcpayserver/btcpayserver.org#110]
I Noticed this error when [Btcpayserver.org](https://btcpayserver.org/) has fully loaded on the browser

* => Two images Are supposed to be in the Home page But aren't Loading.

* => The Images only show when you switch between dark/light Modes, thereby switching URL eg: https://btcpayserver.org/dark/ or https://btcpayserver.org/light/

![image](https://user-images.githubusercontent.com/38410485/79927200-eac37580-8436-11ea-9b6b-82a12d58d072.png)

**Comment by dennisreimann** [comment]
Hmm, it works for me in Firefox, Chrome and Safari – also checked that the references are fine regardless of the theme setting/URL. Can you see if this still fails (potentially just a glitch?) and if so, which browser are you using?

**Comment by Chibuikekenneth** [comment]
I'm using chrome, also tried on Firefox as well but still have the same issue.

Maybe you can try using a different laptop as well or try on mobile phone.

**Comment by dennisreimann** [comment]
Just checked, works on my mobile devices as well. Can you try clearing the cache and reload?

**Comment by Chibuikekenneth** [comment]
*  I have Done that too. Though i tried inspecting, and here's what i got

![image](https://user-images.githubusercontent.com/38410485/80016915-aa620700-84cb-11ea-9bfe-f587763fbd98.png)

URL: [btcpaysever.org](https://btcpayserver.org/)

*  When it's in either light or Dark mode, the image Shows, when i inspect, i get the image

![image](https://user-images.githubusercontent.com/38410485/80017221-2a886c80-84cc-11ea-8d42-6b0d7d92e71a.png)

**Comment by dennisreimann** [comment]
Ok, thanks for digging deeper, you are correct! Can't check why it is working for me though, but this will be fixed with #108.

**Comment by Eskyee** [comment]
<img width="1398" alt="Screenshot 2020-04-25 at 07 33 14" src="https://user-images.githubusercontent.com/30862925/80273563-24141380-86cb-11ea-9891-973cfafe136a.png">

I'm also seeing this today on my safari , @dennisreimann  

find broken lmg links below...
https://btcpayserver.org/img/invoice-%7B%7B_thrFor%7D%7D.svg

https://btcpayserver.org/img/server-%7B%7B_thrFor%7D%7D.png

**Comment by dennisreimann** [comment]
Ok, let‘s get #108 merged. Ping @vswee @pavlenex.

**Comment by pavlenex** [comment]
Please @Chibuikekenneth and @Eskyee check now and let us know if still happens, if not then we can close the issue. (clear your browser cache just in case)

**Comment by Eskyee** [comment]
<img width="1398" alt="Screenshot 2020-04-25 at 08 28 37" src="https://user-images.githubusercontent.com/30862925/80273976-f335dd80-86ce-11ea-9810-06160b452362.png">

yes working now, cleared cache, now all good!

**Comment by Chibuikekenneth** [comment]
Yes !!!

Cleared cache, All Good. @pavlenex
