### ISSUE TITLE
Chromium Browser (page view issue)

### ISSUE THREAD

**Issue by praneetjainIN** [btcpayserver/btcpayserver.org#114]
Try opening the website in chromium browser, the page is not aligned at all. 

Home page is too stretched. Rest pages seems fine. 

![image](https://user-images.githubusercontent.com/63642550/80303947-e8fc0800-87d0-11ea-83ad-5e88d7e5a5cd.png)

![image](https://user-images.githubusercontent.com/63642550/80303970-029d4f80-87d1-11ea-9a2c-0cccc5cbe798.png)

![image](https://user-images.githubusercontent.com/63642550/80303985-1779e300-87d1-11ea-8ef8-297843438a72.png)

**Comment by Eskyee** [comment]
I tested this error on other browsers and can't reproduce problem , chromium browser might have a bug?? not sure 100% because I don't use chromium browser sorry.

**Comment by dennisreimann** [comment]
Tested and can verify this is working.
