### ISSUE TITLE
Switching between languages on mobile

### ISSUE THREAD

**Issue by l33d4n** [btcpayserver/btcpayserver.org#128]
When trying to switch between languages the menu "jumps" after clicking on the languages dropdown and automatically clicks on the first language, it is impossible to select the desired language.

## Screen recorder
![ezgif-2-168f689c2a37](https://user-images.githubusercontent.com/8020386/90591104-c923a080-e214-11ea-8fb0-e05e0aeb686b.gif)

**Comment by pavlenex** [comment]
Thanks for reporting this is indeed a bug. Replicated on Safari.

**Comment by Zaxounette** [comment]
Nice find ! 
Also confirmed in Chrome on Android.
