### ISSUE TITLE
W3C errors list

### ISSUE THREAD

**Issue by l33d4n** [btcpayserver/btcpayserver.org#133]
I fixed almost half of the errors in #130 but there is still some work to be done.

Full list: https://validator.w3.org/nu/?doc=https%3A%2F%2Fbtcpayserver.org%2F

![image](https://user-images.githubusercontent.com/8020386/93042559-f0d61f00-f681-11ea-86d2-abdc53a09f4e.png)

**Comment by pavlenex** [comment]
Here's what's left.
![Screenshot 2020-09-17 at 09 45 26](https://user-images.githubusercontent.com/36959754/93436036-8d8afd80-f8ca-11ea-9651-c435c0e8c26b.png)

**Comment by l33d4n** [comment]
![image](https://user-images.githubusercontent.com/8020386/94338494-4c5ec000-0025-11eb-8abd-32cecaf17d3f.png)

**Comment by Zaxounette** [comment]
Concerning sections 1.1 and 1.2, after looking up the docs on language tags, it seems Great-Britain isn't a valid country name/code/tag.
Instead, should use United-Kingdom `en_UK`.

**Comment by l33d4n** [comment]
@Zaxounette I'm not sure how to change it without breaking the translation but it seems the correct code is ```en-GB``` instead of ```en_GB```:
https://www.w3.org/International/articles/language-tags/#region

![image](https://user-images.githubusercontent.com/8020386/95668024-99ec3880-0ba0-11eb-92fd-49edbb9c017c.png)

**Comment by Zaxounette** [comment]
@l33d4n Oh my bad ! 
You are correct on the `-` instead of `_`. 
As for UK vs GB, since they give that example directly in the docs, i'll assume they're right too :D

**Comment by Zaxounette** [comment]
Changing that without breaking translation might just be a question of tagging it the same way for the string file ?

**Comment by l33d4n** [comment]
To be honest, I'm not really sure how transifex works. 
I believe that we need to change the language tags and update it with Transifex.

I think that the process is similar to adding a new language, make sense?

**Comment by Zaxounette** [comment]
> To be honest, I'm not really sure how transifex works.
> I believe that we need to change the language tags and update it with Transifex.
> 
> I think that the process is similar to adding a new language, make sense?

I'll ping @Britttttk, she'll know how to answer that better than me.
