### ISSUE TITLE
SecurityHeaders Report Summary for BTCPayServer. org  scored a low D

### ISSUE THREAD

**Issue by esky33kubernetes** [btcpayserver/btcpayserver.org#137]
https://securityheaders.com/?q=btcpayserver.org&followRedirects=on

thought I share it here... as I was researching securityheaders!! So if maybe we could improve the scoring on our securityheaders, for .org site but as we host site on GitHub , I,m not sure how this works!! may be @dennisreimann or @vswee understands this more clearly. 
cheers

**Comment by NicolasDorier** [comment]
Well I think that's OK given the website is not really security sensitive. But if we can do something, why not.

**Comment by dennisreimann** [comment]
I've tried setting these headers via html meta tags (e.g. `<meta http-equiv="X-Frame-Options" content="deny">`), but this does not work and they should be set properly as HTTP headers. GitHub Pages does not support this, so the solution would be to switch to something like Netlify or use a reverse proxy in front of the site.

As Nicolas said this isn't really relevant and necessary in this context.
We can accept this, given that the options don't seem worth the effort.

**Comment by Eskyee** [comment]
Yes I agree!

**Comment by mariodian** [comment]
This may however be an issue for [apps or the btcpay server itself](https://securityheaders.com/?q=https%3A%2F%2Fmainnet.demo.btcpayserver.org%2Fapps%2F87kj5yKay8mB4UUZcJhZH5TqDKMD3CznjwLjiu1oYZXe%2Fpos&followRedirects=on), especially when it comes to `Content Security Policy`.

**Comment by Eskyee** [comment]
Be nice just to double check all this.... if it can protect the user .. etc etc
