### ISSUE TITLE
Make developer docs / API more prominent

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver.org#139]
Our new [API ](https://docs.btcpayserver.org/API/Greenfield/v1/)is currently quite hidden as mentioned [here](https://github.com/btcpayserver/btcpayserver/pull/2127).

We should discuss on how to display the link to the API more prominently on the website.

**Comment by dennisreimann** [comment]
We could add a fifth point "Automation via the API" with an introduction text like I mentioned [here](https://github.com/btcpayserver/btcpayserver/pull/2127#issuecomment-743111914) to the selling points section.

Other than that I think one would expect to find it more prominently in the docs than on the website. For that I still see a use case for the "Explore by topic" section, which we discussed [here](https://github.com/btcpayserver/btcpayserver-doc/pull/545#issuecomment-656668620).

**Comment by pavlenex** [comment]
@dennisreimann  That sounds good to me. Also I'd add `Developers` in the menu with `API` sub-menu, and later on docs and plugins for devs. If you're tackling the copy on the site, please try to make it simple to understand and easy to translate.

**Comment by pavlenex** [comment]
Awaiting for the icons from @dstrukt to proceed.
