### ISSUE TITLE
Idea: Layaway for lightning?

### ISSUE THREAD

**Issue by neurofighter** [btcpayserver/btcpayserver.org#142]
With limited inbound capacity it would really help if there was a layaway feature for lightning payments.  If I could choose how much to pay at each payment, I could pay out of my send capacity, then load up some more bitcoin onto my lightning channels through a strike payment or loop in.  After a couple of payments when the invoice is paid off then I could receive my item.

**Comment by pavlenex** [comment]
This is a wrong repository for suggestions, you may want to suggest this on chat.btcpayserver.org or in our main repo discussions section.

**Comment by neurofighter** [comment]
Ok thanks. I posted the comment in the lightning mattermost channel
