### ISSUE TITLE
Blog feed not found

### ISSUE THREAD

**Issue by bubelov** [btcpayserver/btcpayserver.org#149]
Hi. Did you remove RSS feed intentionally of it's just a bug or temporary measure? I'm getting 404 on https://blog.btcpayserver.org/feed/ in my reader, apparently this was a valid feed URL for a long time until recently.

**Comment by pavlenex** [comment]
Hey, thanks for reporting, this could be due to our firewall aggressively blocking certainly URL's, I'll take a look.

**Comment by pavlenex** [comment]
We're migrating our blog to a new CMS. Development process is here https://github.com/btcpayserver/blog if this feature is useful, we can certainly try to add it back. Feel free to request the RSS addition in that repo.
