### ISSUE TITLE
Find a way to prominently display "BTCPay For Local Communities" video?

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver.org#150]
There's really a nice video made by Brian that gives people the hands-on BTCPay Server experience. https://youtu.be/9n81qnzlPf8

It would be a good idea to showcase this somewhere on the site.

I'm not 100% sure of the best practices for showcasing multiple videos on the front page. Maybe @dstrukt or @gbks can advise here.

**Comment by Zaxounette** [comment]
Not sure if it's best practice, but I know videos carousels can be done.

We have the original video in the middle of the site, we could add Brian's video in a carousel alongside it, and then add the animation N°2 alongside those in the carousel once it's ready.

**Comment by GBKS** [comment]
As @Zaxounette wrote, a horizontal carousel is a common solution. If you just have two videos, you could also just stack them vertically and avoid the extra complexity (carousels are great for 3+ items IMHO). I'd make sure that video titles are easy to see, so a user can pick the one that best fits their interests. The video currently on the BTCPay home page is just a green gradient without a title, and I can't tell what the video will be about.

**Comment by pavlenex** [comment]
I guess having them side by side makes sense.

**Comment by ghost** [comment]
Happy to take this one along with #151.

**Comment by dstrukt** [comment]
> As @Zaxounette wrote, a horizontal carousel is a common solution. If you just have two videos, you could also just stack them vertically and avoid the extra complexity (carousels are great for 3+ items IMHO). I'd make sure that video titles are easy to see, so a user can pick the one that best fits their interests. The video currently on the BTCPay home page is just a green gradient without a title, and I can't tell what the video will be about.

Sorry for the delay in response, been with family this weekend.

+1 To either a horizontal or vertical stack unless we have 3-4+ videos for a carousel. It's a nice potential solution, but I don't think we're quite there, and depending on context, the videos they could be slightly dispersed among the page, so it's not an immediate one after the after in either direction .. but that change could be addressed at a later date.

+1 To properly labeling the intro/outro screens on our videos, with a title, and short description (if the title doesn't cover it), to give the end-user an idea of what they're about to watch / encourage that click, and ending with potential CTAs or social media information.

Great video though, glad it's getting surfaced!

**Comment by ghost** [comment]
Can this and #151 be closed? It's been a while but I think #152 resolved both.
