### ISSUE TITLE
Change the thumbnail of the introductory video

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver.org#151]
The introductory video we have on-site, looks like something is broken, we should instead showcase a better thumbnail.

![image](https://user-images.githubusercontent.com/36959754/124447807-06881280-dd82-11eb-8e32-068c5820f2a6.png)

**Comment by ghost** [comment]
An easy fix would be so change the thumbnail to the BTCPay logo:

![image](https://user-images.githubusercontent.com/4956763/124472235-8b852300-dda6-11eb-820a-646e0a441abb.png)

The fade-out screen at the end of the video could be another nice option:

![image](https://user-images.githubusercontent.com/4956763/124472432-ca1add80-dda6-11eb-9edc-f780b168eba6.png)

Another reason that the video appears broken is that the big play button is missing (as seen above), at least when viewed on desktop. On mobile, the play button appears as it should:

![image](https://user-images.githubusercontent.com/4956763/124473818-70b3ae00-dda8-11eb-9d3e-34326ee0b9fb.png)

Thoughts?

**Comment by dstrukt** [comment]
I like where you're going with the outro / trailing screen (logo / socials), but I think the intro screen could potentially use a nice bold (left or center aligned) title our the Open Sans font.

Should have some time this weekend to mock out something.
