### ISSUE TITLE
Add Shopify Icon to the website and link to shopify docs

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver.org#161]
![Screenshot 2022-04-19 at 11 45 47](https://user-images.githubusercontent.com/36959754/163976983-56d06fe0-5cf0-449a-a413-3eaa0b45650f.png)

https://docs.btcpayserver.org/Shopify/

**Comment by OpenSourceLasagna** [comment]
it would be really nice if i could do this as my first issue!

**Comment by pavlenex** [comment]
Awesome @Paul0908 It's all yours! ❤️

**Comment by dennisreimann** [comment]
Done with #164.
