### ISSUE TITLE
Replace old `what is btcpay` with the new what is btcpay server video

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver.org#162]
We have a better video that should replace the old one, or if we find a way to better present videos we can keep the old one as well.

![Screenshot 2022-04-23 at 17 30 26](https://user-images.githubusercontent.com/36959754/164912752-d59377e1-511a-4e5b-a266-d7e52b2d5980.png)

The new video https://youtu.be/XHj7EVUunJ4

**Comment by ghost** [comment]
@pavlenex I can take this one as a first issue

**Comment by plmdie** [comment]
I've added a pull request to your repository.

**Comment by plmdie** [comment]
Hi, i can add the corrected Qr code to the SVG but i didn't found a QR Generator that makes a code exactly equal to the one in the image.

![image](https://user-images.githubusercontent.com/100805793/165049641-282580fa-d46a-4ac3-801b-a46aa28f8ada.png)

Is this good enough?

**Comment by pavlenex** [comment]
Yes, it's good enough no worries😄

**Comment by pavlenex** [comment]
you're probably reffering to this issue #158

**Comment by plmdie** [comment]
Yes, I'm in the wrong place, sorry.
I'll do it today.
Also unrelated, but i applied to the team of pt-pt and es-es to Transifex, but i was still not added.
