### ISSUE TITLE
Add link to Telegram in the footer

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver.org#172]
As explained here https://github.com/btcpayserver/btcpayserver/issues/4158 we should add a link to our official telegram chat in the Footer.  https://t.me/btcpayserver

I also think we should rename chat to "Mattermost" or "Mattermost Chat"? But that can be done in a a different issue/pr.

**Comment by sreejasaha19** [comment]
Hey, I want to contribute to this issue. Can I work on this issue? If yes, could you please assign it to me.

**Comment by pavlenex** [comment]
Sure @sreejasaha19 feel free to :)

**Comment by vaibhavgarg237** [comment]
I think it's already done by someone https://github.com/btcpayserver/btcpayserver/pull/4160

**Comment by daviogg** [comment]
I already publish PR yesterday evening, I don't get if I need also to rename the Mattermost reference
![image](https://user-images.githubusercontent.com/33121159/192150065-bcf3beec-3729-48c6-a310-64100bc8d901.png)

**Comment by pavlenex** [comment]
No this PR you referred to is for server itself, and this issue is for btcpayserver.org

**Comment by vaibhavgarg237** [comment]
> No this PR you referred to is for server itself, and this issue is for btcpayserver.org

oh yes, I just noticed

**Comment by vaibhavgarg237** [comment]
> As explained here [btcpayserver/btcpayserver#4158](https://github.com/btcpayserver/btcpayserver/issues/4158) we should add a link to our official telegram chat in the Footer. https://t.me/btcpayserver
> 
> I also think we should rename chat to "Mattermost" or "Mattermost Chat"? But that can be done in a a different issue/pr.

![image](https://user-images.githubusercontent.com/67408018/192153390-e226b76d-36ca-4079-9ed8-e2c72c9dfc57.png)
Here it's already written "Mattermost", where are you referring to "chat"?
