### ISSUE TITLE
according to [user feedback](https://t.me/btcpayserver/70021) the translations (german was reported, spanish tested on my end) for the buttons and text around them are missing:

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver.org#197]
according to [user feedback](https://t.me/btcpayserver/70021) the translations (german was reported, spanish tested on my end) for the buttons and text around them are missing:

![grafik](https://github.com/btcpayserver/btcpayserver.org/assets/1374810/4ac40b21-b355-4d1d-8721-39aeddd45713)

@dennisreimann 

_Originally posted by @petzsch in https://github.com/btcpayserver/btcpayserver.org/pull/195#issuecomment-1962591700_

**Comment by pavlenex** [comment]
We could should either show English strings when a string is missing or in this particular use chatgpt to translate them ourselves since they're simple to translate and no context is needed.

**Comment by dennisreimann** [comment]
Added the english fallback and reduced the completeness threshhold to 80 percent, because we recently added a few strings and some languages weren't displayed anymore.
