### ISSUE TITLE
Add nopCommerce integration on the website

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver.org#200]
Just like we did for SmartStore in https://github.com/btcpayserver/btcpayserver.org/pull/194 we should now add nopCommerce icon and link to the integration https://www.nopcommerce.com/en/btcpay-server-accept-bitcoin-payments

I wanted to add a link to docs instead, but I think directly linking to a marketplace is more appropriate since it has better call to actions to download plugin followed by good description.

**Comment by pavlenex** [comment]
@TChukwuleta In case you'd like to tackle it, feel free to.

**Comment by TChukwuleta** [comment]
sure. I would
