### ISSUE TITLE
Replace Tor with OpenCart, rename Integrations and plugins title with e-commerce integrations and add VirtueMart/Joomla

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver.org#203]
As did in #201 we should replace Tor svg icon (and remove it) with OpenCart and rename the title, since there are no plugins there and it's confusing now that we have plugin system. 

- [ ] Rename Integrations and plugins to E-Commerce Integrations.
- [ ] Remove Tor icon and replace it with [OpenCart](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=44269) integration
- [ ] Add Joomla/Virtuemart [integration](https://extensions.joomla.org/extension/vm-payment-btcpay-for-virtuemart/)

**Comment by pavlenex** [comment]
@TChukwuleta if you wish feel free to tackle it?

**Comment by pavlenex** [comment]
@ndeet Open question here, should we say say Joomla or VirtueMart integration, I've noticed plugin says VM, but it's on Joomla.org, for me these are a bit mutter, hopefully you can clarify.

**Comment by TChukwuleta** [comment]
sure @pavlenex

**Comment by ndeet** [comment]
@pavlenex yes we should mention Joomla! I think, it is just that there are many different [ecommerce solutions](https://extensions.joomla.org/category/e-commerce/e-commerce-integrations/) for Joomla available so writing only Joomla! might be not enough?

**Comment by pavlenex** [comment]
@ndeet So you're saying on btcpayserver.org it should referenced as Joomla VirtueMart?
