### ISSUE TITLE
Add whmcs integration to the website 

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver.org#205]
As we did in https://github.com/btcpayserver/btcpayserver.org/issues/203 and https://github.com/btcpayserver/btcpayserver.org/issues/200 we've finally added new itegration to the marketplace. 

Task is simple, to integration section of the website:

- add logo
- add link https://marketplace.whmcs.com/product/7348-accept-bitcoin-payments-with-ease-and-no-fees-btcpay-server-for-whmcs

**Comment by pavlenex** [comment]
@TChukwuleta go for it if you want 😄

**Comment by TChukwuleta** [comment]
😃 sure
