### ISSUE TITLE
Donation Button

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver.org#28]
Donations plunged since we removed them from the above the fold.
We should probably have `Donate` button next to the `Live Demo`.

**Comment by vswee** [comment]
ICYMI: Interim changes to mainstream site live at [btcpayserver.flat18.co.uk](https://btcpayserver.flat18.co.uk/) and wild but not entirely useless stuff lives at [experimental-btcpayserver.flat18.co.uk](https://experimental-btcpayserver.flat18.co.uk/)
