### ISSUE TITLE
Correction and clarification on English strings

### ISSUE THREAD

**Issue by huey735** [btcpayserver/btcpayserver.org#31]
To be corrected
- "Maximum privacy for you and your **customers.Running** a full node. No AML/KYC."

- "Having a technical question not covered in docs or want to help improve the code? Help us out on **GitHib**."

Suggestion
- "Bitcoin" shouldn't be capitalized when referring to the token ("They paid me in euros but I'd prefer bitcoins")

**Comment by pavlenex** [comment]
Thanks, will address these.

> "Bitcoin" shouldn't be capitalized when referring to the token ("They paid me in euros but I'd prefer bitcoins")

Can you provide specific places where this happens?

**Comment by huey735** [comment]
- "Receive your Bitcoin and altcoin payments without any fees or third-party involvement. You are your own payment processor. Funds go directly to your wallet; your private key is never required."
- "Receive Bitcoin payments as a business or an individual. No fees. No third-party."
- "Your keys - Your Bitcoin. Private key never required for using BTCPay."

**Comment by pavlenex** [comment]
Done in #32 thanks for reporting.
