### ISSUE TITLE
All Letters In Upper Case

### ISSUE THREAD

**Issue by xsedivy** [btcpayserver/btcpayserver.org#34]
The main page text "Start Accepting Bitcoin Payments With 0% Fees & No Third-Party" automatically change first letters to upper case in localized page versions. This might be OK in English but looks very silly for languages like Slovak a I believe many others

![UpperCase](https://user-images.githubusercontent.com/9197036/58991198-f0e14100-87e7-11e9-878b-37fe65e35416.png)

**Comment by vswee** [comment]
Great feedback. Thanks for that @xsedivy
