### ISSUE TITLE
Extra text "Lightning network"

### ISSUE THREAD

**Issue by xsedivy** [btcpayserver/btcpayserver.org#35]
There is extra text which is not present in source - looks like this is repro for all languages
![image](https://user-images.githubusercontent.com/9197036/58991967-d7d98f80-87e9-11e9-8801-b2e83e8f4484.png)

Everything looks good on Transifex

**Comment by vswee** [comment]
Well spotted. It appears some translators have maintained the name "Lightning ...node ...network", etc. while others have translated it. This is may be a nuance in those languages and I'm not really able to determine if it's an error myself. 

Please contribute to the translation effort if you can on https://www.transifex.com/btcpayserver/btcpayserver-website/ and get in touch with @britttttk on https://chat.btcpayserver.org/btcpayserver/channels/translations if you haven't already. Also feel free to re-open this issue if there's something amiss.

**Comment by xsedivy** [comment]
I think this is a different issue. It looks like English page text is just one resource, but in localized versions it is a combination of these two resources:

![image](https://user-images.githubusercontent.com/9197036/58994266-36a20780-87f0-11e9-9858-f4c50ef13348.png)

If you check other languages there is a missing full stop before last sentence almost for all languages - looks like just for those where the second resource not equal source text. Issue is not repro on Spanish for example:

![image](https://user-images.githubusercontent.com/9197036/58994434-c1830200-87f0-11e9-8fa6-a5b35a04d635.png)
