### ISSUE TITLE
Some languages without code

### ISSUE THREAD

**Issue by xsedivy** [btcpayserver/btcpayserver.org#36]
![image](https://user-images.githubusercontent.com/9197036/58992297-bc22b900-87ea-11e9-8b18-a035c43912c9.png)

I think it might be better to either add language code for all languages or remove it everywhere. This way it looks strange...

**Comment by vswee** [comment]
Again, great feedback. We’ll deffo take that on board and churn out some adjustments. Feel free to drop more feedback on the #website channel on chat.btcpayserver.org.

**Comment by vswee** [comment]
Implemented in demo version https://btcpayserver.flat18.co.uk for review before being pushed to main site. Feel free to re-open if I've missed something or drop us a line on https://chat.btcpayserver.org

**Comment by xsedivy** [comment]
Looks good
