### ISSUE TITLE
can we add coded with love at the end of copyright?

### ISSUE THREAD

**Issue by Karem-sobhy** [btcpayserver/btcpayserver.org#37]
i think it will be cute
BtcPay Server Coded for you with ❤ !

**Comment by britttttk** [comment]
@kemoantemo You're saying in the footer of the website right?

I like the idea but perhaps more emphasis on the idea that everything is done by the community.
Also coders are not the only contributors :)

Maybe: BTCPay Server Community Created with ❤ !

**Comment by Karem-sobhy** [comment]
Nice i like ur phrase more than mine

**Comment by vswee** [comment]
`BTCPay Server Community Created with `❤` ! Website built with `⚡` by flat18.` might work too. After @britttttk works her semantic rewriting magic :)

**Comment by pavlenex** [comment]
I don't see why we should add more strings for translators, imo it's good the way it is now. The least Ed deserves is a link back and a credit for all the work he's done on the website.

**Comment by Karem-sobhy** [comment]
@pavlenex i didn't say that we should remove ed's credit he sure deserve it i said we can put it in the end of the credits and the copyright and it will not be much issue 1 more string and we even could leave it in English it's not something essential to translate

**Comment by pavlenex** [comment]
Same, NACK from me as I visually already think our footer already has too much stuff going on.
![Screen Shot 2019-06-17 at 22 40 48](https://user-images.githubusercontent.com/36959754/59635242-02fca100-9151-11e9-875f-6fe9a61b52e0.png)

**Comment by Karem-sobhy** [comment]
i don't see what is the problem to add a 1 new line in it and it's not even a problem that it have much stuff they are good ordered in widescreen and mobile screen so there is no harm of being too much stuff

**Comment by vswee** [comment]
Let’s play around with the footer text on the playground site and hold off on asking the community to translate it on until there are more major strings changes to lump together. The idea being that we prudently limit the amount of requests we make to the amazing translators. I’m not for mixing any English in with the translated pages if it can be avoided. 

Edit: @kemoantemo it’s not my choice what is done by the way. The above is just my suggestion. Let’s talk more about it on website channel on chat

**Comment by Karem-sobhy** [comment]
ok guys not a problem it was just a cute suggestion <3
