### ISSUE TITLE
Default Donation amount gets cut off

### ISSUE THREAD

**Issue by radWorx** [btcpayserver/btcpayserver.org#43]
In Chrome:
![image](https://user-images.githubusercontent.com/27673545/62334560-25931100-b496-11e9-8af9-6e95efc6a47c.png)

**Comment by vswee** [comment]
Tiny css change to the `min-width` live on playground: [https://btcpayserver.flat18.co.uk/](url). Should fix that issue for you @radWorx but let me know anything else you find :) Cheers
