### ISSUE TITLE
Spelling error on donation page

### ISSUE THREAD

**Issue by britttttk** [btcpayserver/btcpayserver.org#48]
Foundation on [donation page](https://btcpayserver.org/donate/). 

Does this change need to be made on Transifex first or make a PR here first? I'm not sure of the workflow for BTCPay website + Transifex.

![image](https://user-images.githubusercontent.com/39231115/66286913-b91b0080-e890-11e9-8780-3778f9b45eab.png)

**Comment by pavlenex** [comment]
There a [source file](https://github.com/btcpayserver/btcpayserver.github.io/tree/master/source) - `src`, up there you can apply the change to the HTML which will automatically bump translations, it's also lightly documented (readme in souce)

**Comment by pavlenex** [comment]
Actually, it seems that /donation page is not in source for some reason.
