### ISSUE TITLE
[Discussion] Remove carousel and simplify the features layout

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver.org#55]
Our carousel may be overkill.

What do you guys think, should we simplify and show features in a different layout?

https://bisq.network/ is a good and clean example imo, but web-devs feel free to discuss.

**Comment by ghost** [comment]
I agree that the carousel looks overkill, plus (at least from my experience) it doesn't feel very smooth.

For me the "natural" way of navigating the content of a page has always been vertically (I guess the rise of vertical parallax-scrolling agrees with that), in that regard bisq's feature section definitely feels better and is also easier to skim for information since it's available all at once.

What I could imagine would be a bisq like placement of the cards that are currently used in the carousel, but with with a fixed size and 2-3 in a row.
In case there is a youtube video or a link list connected to the card, a modal dialog would pop up on click in which the youtube video or link list is embedded and accessible.
This would maintain basically all the information but clean up the view.

**Comment by pavlenex** [comment]
That seems like I good approach @melanisticmanticore, I quite like that idea.

**Comment by vswee** [comment]
I'm all for killing the carousel. Good opportunity to refine those features from 12 to maybe 8 if possible.

**Comment by pavlenex** [comment]
Sounds like a plan then. Okay let's discuss which features we want on the website.

**Comment by ghost** [comment]
So I just picked up on @vswee s idea here (reducing the count to 8).
We should probably change the wording a bit as well but these are the features I believe should definitely be on the list.

- Receive bitcoin payments as a business or an individual. No fees. No third-party.

- Free and fully-open source software. Self-hosted and non-custodial.

- Diverse deployment options. From VPS cloud to Raspberry Pi hosting

- Accept micro payments via the Lightning Network. Self-hosted Lightning Node.

- E-commerce integrations: WooCommerce, Drupal, Presta, Magento and more.

- Maximum privacy for you and your customers. Running a full node. No AML/KYC.

- Get paid in person or online with a built-in web Point of Sale app.

- Accounting made easy with Quick Book integration and invoice export.

~~Easily add payment buttons for tips and donations on your website.~~
*Seems self-explanatory*

~~Your keys - Your bitcoin. Private key never required for using BTCPay.~~
*Seems self-explanatory in regards of being open-source and fully self-hosted.*

~~Complete technology stack that allows you to become a payment processor for yourself or others.~~
*Seems self-explanatory after reading the info-text beneath the menu.*

~~Opt-in integrations for several altcoins, maintained by their respective communities.~~
*Not quite sure actually, maybe leave it in but just as a mention in a different feature (open source maybe)*

What do you guys think?

**Comment by pavlenex** [comment]
@melanisticmanticore sorry for the late reply.

I wouldn't limit it to 8 features, because there may be a few more that are quite important, like an [Internal Wallet](https://docs.btcpayserver.org/features/wallet). As far as alts are concerned, I'd probably mention them briefly and link to a page where people can learn more, def not something that should be a feature on its own.

 The approach you outlined sounds good to me. Feel free to tackle the issue if you want.

**Comment by ghost** [comment]
No worries 😃 

Will keep in mind what you said, I'd actually like to tackle it.

Is there a dev server or CLI or something alike that gives me a "build" of my changes to the template?

I will check tomorrow and try to figure the whole transifex thing out by myself in case there's no reply. Maybe I'll figure out that it was a stupid question but my web-dev expertise revolves mostly on working with mono-language angular apps until now, so forgive me that I'm a bit lost here 😄

**Comment by pavlenex** [comment]
Cool, assigning this one to you then.

Check out the [readme](https://github.com/btcpayserver/btcpayserver.github.io#source-files), but I'm not sure if it's enough info. @vswee wants to improve those docs in the future, but if you need help there's #[website channel on our mattermost.](https://chat.btcpayserver.org/btcpayserver/channels/website)

**Comment by vswee** [comment]
@melanisticmanticore if you want to talk design, suggest changes, implement yourself --whatever. I'll point you to where the changes go :) I think we're aiming for something bisq-y but we can brainstorm on #website.

**Comment by vswee** [comment]
@pavlenex as for limiting the count; maybe these beauties will change your mind :P
![Screen Shot 2019-10-24 at 15 05 20](https://user-images.githubusercontent.com/2403100/67517303-538c8980-f670-11e9-951d-184e5b258373.png)
![Screen Shot 2019-10-24 at 15 05 31](https://user-images.githubusercontent.com/2403100/67517309-57b8a700-f670-11e9-98e2-1eafb4d4c510.png)

**Comment by pavlenex** [comment]
@vswee Def something like that, let's leave @melanisticmanticore lead on this one? 
And we'll together brainstorm on the design and content. We'll have to apply certain changes to the content as well to fit the new layout.
