### ISSUE TITLE
Payment button page

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver.org#63]
We should have a payment button demo page to demonstrate different options of the payment button.

**Comment by vswee** [comment]
~~Could this be the place for this https://experimental-btcpayserver.flat18.co.uk/buttons/index.cshtml?~~

~~https://btcpayserver.flat18.co.uk/buttons~~

**Comment by pavlenex** [comment]
Yup @vswee but I guess we now need to make it appeal more like the main site (header/footer). Since when we were discussing this, we wanted to make it as a part of the store page, but I guess it makes more sense to have it as a page belonging to the main site, what do you think?

Fantastic page by the way.

**Comment by vswee** [comment]
I Agree it feels like a natural part of the main site to have the button examples there.

**Comment by Ivans1310** [comment]
Where could I create a payment button?

**Comment by vswee** [comment]
> Where could I create a payment button?

~~The sample is: [on the demo](https://btcpayserver.flat18.co.uk/buttons)~~

**Comment by Eskyee** [comment]
404 error on URL https://btcpayserver.flat18.co.uk/buttons @vswee 

or is this on purpose ?? as you can do this in your local dev environment now..
please update us please. https://btcpayserver.flat18.co.uk 

thanks @vswee @pavlenex

**Comment by vswee** [comment]
@Eskyee This is on purpose mate :( 
Sorry about that broken link.
