### ISSUE TITLE
Individual Donations section - add PR link

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver.org#64]
It's currently unclear to new contributors how they can add themselves to the list of individual contributors.
![Screenshot 2019-10-24 at 09 15 52](https://user-images.githubusercontent.com/36959754/67462643-4bb4f100-f640-11e9-8b84-756394e1bf7c.png)

I propose we add a sentence at the end of the list with a link to the [tmpl.html](https://github.com/btcpayserver/btcpayserver.github.io/blob/master/source/src/html/donate/tmpl.html)

Something like: BTCPay Contributor? [Add yourself to the list.](https://github.com/btcpayserver/btcpayserver.github.io/blob/master/source/src/html/donate/tmpl.html)

**Comment by vswee** [comment]
I second that. Would be linking it to [/source/src/json/donations.json](https://github.com/btcpayserver/btcpayserver.github.io/blob/master/source/src/json/donations.json) of course ;)

**Comment by pavlenex** [comment]
LGTM @vswee 🚀
