### ISSUE TITLE
404 Page not found Getting Started

### ISSUE THREAD

**Issue by jguchte** [btcpayserver/btcpayserver.org#66]
Hi,

the link to https://docs.btcpayserver.org/btcpay-basics/gettingstarted returns "404 Page not found".

Info:
https://btcpayserver.org/
Getting Started at a the bottom of the page at BTCPAY BASICS

Greetings,
Jason.

**Comment by Kukks** [comment]
@pavlenex  can we put a placeholder page on this saying "this page has moved"

Or a redirect tothe new page if possible?

**Comment by pavlenex** [comment]
@Kukks I don't think so, we'll just change it to https://docs.btcpayserver.org/getting-started/ which redirects to a newly re-structured guide.
