### ISSUE TITLE
Footer restructure

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver.org#69]
It seems that our footer on the main website has a bit too much info, and it's not even organized properly imo.

Let's discuss here how we can make it more useful and less cluttered for visitors.

**Comment by dennisreimann** [comment]
Just a note: The "Getting Started" link currently does not work, it should point to this URL: https://docs.btcpayserver.org/getting-started/

**Comment by pavlenex** [comment]
This is now done, thanks Mike, Ed and Dennis for brainstorming and killing the monster.
