### ISSUE TITLE
btcpay video, loading strange .org site

### ISSUE THREAD

**Issue by Eskyee** [btcpayserver/btcpayserver.org#70]
<img width="1436" alt="Screenshot 2019-10-28 at 09 56 00" src="https://user-images.githubusercontent.com/30862925/67669574-1246f300-f96a-11e9-92b2-b85c5c9ee7fa.png">

btcpay video seems to load strange ?? the view is not correct ?? 

cheers

**Comment by pavlenex** [comment]
[b7d0159](https://github.com/btcpayserver/btcpayserver.github.io/commit/b7d0159d0aac6d9c7969e8f28bc3b78444f626e1)
