### ISSUE TITLE
Change translations to include source strings

### ISSUE THREAD

**Issue by ndeet** [btcpayserver/btcpayserver.org#76]
Change proposed after switch of the build system in #75:

Currently translations are placed in template files via some array index of a variable (e.g. `$j[5]` like here:
```
<a alt="$j[37]" class="promoButton p-1" href="https://mainnet.demo.btcpayserver.org"
                            target="blank_">
                            <span>$j[37]</span><input class="cu_" /></a>
```

I find this really confusing to read, you always need to check the en translation file `en.json` and count the lines (starting from 0) to get the correct string, this is tedious when you are not familar with the codebase. I would suggest that we use the EN source string always in those template files with some special placeholder markup like `%%` (do not care which one). 

So above example would look like this:
```
<a alt="%%here goes the english source text%%" class="promoButton p-1" href="https://mainnet.demo.btcpayserver.org"
                            target="blank_">
                            <span>%%and here is another text%%</span><input class="cu_" /></a>
```

Another benefit would be that we can extract those strings and generate a `en.json` and not manually maintain all those translations mappings. 

If we agree it makes sense to do it I can give it a shot after the build automation has been merged.

**Comment by pavlenex** [comment]
#103
