### ISSUE TITLE
Features slider on homepage shows empty containers at higher resolutions

### ISSUE THREAD

**Issue by wbnns** [btcpayserver/btcpayserver.org#78]
When browsing the homepage on a larger screen, e.g. 2560 x 1440, empty containers appear in the Features slider:

![image](https://user-images.githubusercontent.com/1130872/71665614-fd1d8480-2d5d-11ea-8757-769fb0294a70.png)

Browser: Chrome Version 79.0.3945.88
OS: Catalina 10.15.2

**Comment by vswee** [comment]
Thanks @wbnns Those blank tiles presently help the focused tile to stay centre of the viewport. Future changes planned for this section will do away with the need for blank tiles entirely.
