### ISSUE TITLE
Payment button link on frontpage is broken

### ISSUE THREAD

**Issue by escapedcat** [btcpayserver/btcpayserver.org#80]
This link on the main page leads to a [broken link](https://store.demo.btcpayserver.org/index.php/payment-button-demo/):

![image](https://user-images.githubusercontent.com/1016218/72258519-91b19d80-360e-11ea-9266-f297eb2554cb.png)

**Comment by NicolasDorier** [comment]
![image](https://user-images.githubusercontent.com/3020646/72413383-0c1b2280-37b3-11ea-82c8-580dacb50dc5.png)

**Comment by NicolasDorier** [comment]
@pavlenex the store is down?

**Comment by pavlenex** [comment]
@NicolasDorier It's not the store. @vswee and I wanted to create a separate html page that will present different payment buttons, since when payment button is embedded in wordpress it's always messed up.

@vswee had some nice ideas, but we never pushed them. Will work on this.

**Comment by pavlenex** [comment]
@NicolasDorier  [This is the current page ](https://store.btcpayserver.org/btcpay-server-payment-button-demo/)and it looks terrible, I'll change the link in the meanwhile but the way our pay button embeds in wordpress makes it look awful.

**Comment by vswee** [comment]
There's still this [experimental buttons](https://experimental-btcpayserver.flat18.co.uk/buttons/index.html) page for what it's worth.
![Screen Shot 2020-01-15 at 14 22 30](https://user-images.githubusercontent.com/2403100/72441378-7b3c4b00-37a2-11ea-8a84-8eb80fc58212.png)

**Comment by pavlenex** [comment]
@vswee that experimental al page looks so much better than the messed up one we have now. If you have the time to simplify it and make it look like btcpayserver.org instead the store page, we can indeed replace the current one.

**Comment by vswee** [comment]
Presumably you'd want to simplify the text and add translations but it's easily theme-able with the environment styles as this [example](https://btcpayserver.flat18.co.uk/buttons/index.html) shows.

**Comment by pavlenex** [comment]
@vswee  That one looks cool. Should we put it as the part of btcpayserver.org or as an external page? I'm thinking we can remove text altogether, we're in website-redesign and re-thinking process anyway, so what do you think about deploying this but without text, with slightly modified footer so it looks the same as btcpayserver.org?

**Comment by vswee** [comment]
Less text the better. You mean to exclude a page title too? Like ~~BTCPay Payment Button demo page~~

**Comment by pavlenex** [comment]
@vswee That one is your call, we can remove it for now if that's alright with you.
