### ISSUE TITLE
[Content] - Improve text on features boxed layout

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver.org#83]
The text we currently have on a demo is just a mockup and we should figure out what to put in those boxes.

![Screenshot 2020-03-23 at 10 47 20](https://user-images.githubusercontent.com/36959754/77303934-06cade80-6cf4-11ea-9581-b5cee801aa3c.png)
![Screenshot 2020-03-23 at 10 47 26](https://user-images.githubusercontent.com/36959754/77303939-07fc0b80-6cf4-11ea-9188-d167538fd9f1.png)

**Comment by pavlenex** [comment]
[Content available here](https://docs.google.com/document/d/1P08F14eIraI7ChtbZWi2XEXkQwMVDQbADF9IaYPTuLY/edit#heading=h.e3izrjqwvc4p)

**Comment by vswee** [comment]
Discretely from the current build method, that content's over here [Content here](https://btcpayserver.flat18.co.uk/loose/)

If you're feeling like a mad lad, all the page text is editable at the click.

**Comment by pavlenex** [comment]
Woah @vswee what an epic solution! Will tackle this one today. Great great job.
