### ISSUE TITLE
[Mobile] Responsive design issues

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver.org#84]
Here's a list of known issues happening on mobile. I'll keep them all logged here so we can tackle the one by one.

### Empty Menu
Some users reported that the menu looks a bit too empty since it's short & simple.

![Screenshot 2020-03-23 at 11 04 41](https://user-images.githubusercontent.com/36959754/77305971-3d562880-6cf7-11ea-9b43-9c3630e00a85.png)

Dub suggested we enlarge the fonts there to make it look bigger and provided an example of what he did for his work as a solution.

![Screenshot 2020-03-23 at 11 12 13](https://user-images.githubusercontent.com/36959754/77305953-33ccc080-6cf7-11ea-8032-eacbcfc3bb09.png)

## Safari iOS
- Mobile menu is empty 
![2020-03-23_10-59-46 (1)](https://user-images.githubusercontent.com/36959754/77305019-9c1aa280-6cf5-11ea-81be-71bf4024372f.gif)

**Comment by vswee** [comment]
Thanks for that @pavlenex 

* Font sized up 50%
* iOS issue fixed

![Screen Shot 2020-03-23 at 16 49 50](https://user-images.githubusercontent.com/2403100/77341262-5fb36a80-6d26-11ea-9cf5-d5618bbbeea1.png)

**Comment by pavlenex** [comment]
Thanks @vswee tested and it works now!

Minor thing, while we're on mobile issues, do you think we can better display these icons? Inline for this size makes sense? 

On iPhone 8.

![IMG_4679](https://user-images.githubusercontent.com/36959754/77341746-7b6f3e80-6d2f-11ea-9ac5-ef1fce93f497.PNG)

**Comment by vswee** [comment]
Even better; all the way down to iPhone SE
<img width="315" alt="Screenshot 2020-03-23 at 17 13 24" src="https://user-images.githubusercontent.com/2403100/77343502-aeaecf00-6d29-11ea-80ad-80882bf2029f.png">

**Comment by pavlenex** [comment]
Awesome! Closing this one then! Waiting for Dub (Mitchell) to provide more feedback so we can proceed.
