### ISSUE TITLE
Make all social icons same size (Mattermost icon is bigger at least visually )

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver.org#86]
Make all icons in `Join The Community` section the same size.
![Screenshot 2020-04-04 at 19 07 06](https://user-images.githubusercontent.com/36959754/78457028-a5b5ea00-76a7-11ea-86c4-1d72bd67243c.png)
Tested on 13" screen.

> Join The Community: For the Desktop viewport the copytext ("BTCPay Server is an open-source project, …") runs too wide. (give it a max-width: 42em; or something similar)

**Comment by vswee** [comment]
<img width="394" alt="Screenshot 2020-04-05 at 21 28 04" src="https://user-images.githubusercontent.com/2403100/78509206-71642b80-7784-11ea-8b1d-7f7a69ce9c48.png">
Better?

**Comment by pavlenex** [comment]
Looks good now @vswee! I'm kinda missing some hover indicator there, should we add that?

**Comment by vswee** [comment]
Added a bounce. Maybe colour is a step too far?

**Comment by pavlenex** [comment]
I don't mind colors but yellow GitHub logo triggers me, perhaps we can use their standard purple logo?
![Screenshot 2020-04-06 at 09 22 36](https://user-images.githubusercontent.com/36959754/78532972-6c38c800-77e8-11ea-94bd-c7760f8a34f1.png)
But could be that it's too much as we already have colors on integration page, your call.
