### ISSUE TITLE
Dark mode - darker color for the footer

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver.org#87]
> Dark theme: The footer should use a darker color, the current green seems too bright

**Comment by vswee** [comment]
![Screen Shot 2020-04-05 at 22 08 37](https://user-images.githubusercontent.com/2403100/78510092-b25f3e80-778a-11ea-9a2d-e0c4b67f2919.jpg)
Changed to the pre-existing dark-green variable (#003822) which is currently the same for both modes

**Comment by pavlenex** [comment]
LGTM!
