### ISSUE TITLE
Improve inconsistent spacing

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver.org#88]
> Spacing: Depending on the breakpoint some spaces look to tight and could be increased (see screenshot)

![spacing-1](https://user-images.githubusercontent.com/36959754/78457570-7bfec200-76ab-11ea-9915-f1a8047a60c9.png)
![spacing-2](https://user-images.githubusercontent.com/36959754/78457573-7c975880-76ab-11ea-8518-88a86733381b.png)

**Comment by vswee** [comment]
![Screen Shot 2020-04-05 at 22 01 37-fullpage](https://user-images.githubusercontent.com/2403100/78509882-48926500-7789-11ea-8b9f-aa93ac4fd020.png)
New 900px-width break-point

**Comment by pavlenex** [comment]
@dennisreimann does this look better now?

**Comment by dennisreimann** [comment]
yep, great!
