### ISSUE TITLE
Determine the text and features in the "Features area"

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver.org#91]
Right now a suggested features area is decent, but I'd like to see if we can somehow improve it since it seems repetitive with the above the fold content. Lots of info gets repeated often, so perhaps it would be better to push something in features that first-time users can understand and get a better feeling of btcpay possibilities either as a payment processor or a stack.

Current features
![features](https://user-images.githubusercontent.com/36959754/78652077-85617780-78c1-11ea-82af-c9e0f55cac3b.PNG)

@vswee made a genius tool https://btcpayserver.flat18.co.uk/loose that allows you to alter text, save it and the share a link with your version for us to preview. It's easier to add text and preview on spot for sure!

**Comment by dennisreimann** [comment]
**Invoices and Accounting**
BTCPay offers the tools that make cryptocurrency bookkeeping easier. Create and manage invoices – and get notified when they get paid. Export your invoices in various formats or integrate them via QuickBooks.

**Wallet Management**
Each of your stores and cryptocurrency have their separate wallets. Create your own private key externally and import the xpubkey – this way you keep your keys secured and you can sign transaction via PSBT or our own BTCPay Vault.

**Apps**
Using the _Point Of Sale_ you can accept cryptocurrencies without fees or a third-party, directly to your wallet. Create and self-hosted your own _Crowdfunding_ campaign or receive tips and donations via the easily customizable _Payment Button_.
