### ISSUE TITLE
en-json contains legacy strings

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver.org#92]
We need to clean up `en-json` since it shows a bunch of legacy strings for people on Transifex. We can't really ask people to translate until we clean it up.

![Screenshot 2020-04-17 at 11 39 52](https://user-images.githubusercontent.com/36959754/79555753-5e186080-80a0-11ea-9e50-b5990582bd14.png)

**Comment by RiccardoMasutti** [comment]
> We need to clean up `en-json` since it shows a bunch of legacy strings for people on Transifex. We can't really ask people to translate until we clean it up.
> 
> ![Screenshot 2020-04-17 at 11 39 52](https://user-images.githubusercontent.com/36959754/79555753-5e186080-80a0-11ea-9e50-b5990582bd14.png)

We can add a `no_translate` label

**Comment by pavlenex** [comment]
I'll leave this here unsure if no_label would help us now, as json was formatted inappropriately from the start.
![Screenshot 2020-04-19 at 11 38 35](https://user-images.githubusercontent.com/36959754/79684524-70c29f00-8232-11ea-9f07-73e55d5e061d.png)
