### ISSUE TITLE
Fix text alignment of the wordpress icon

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver.org#93]
Would be good to remove redundant BTC icons, looks kinda messy. At least on the presta icon the middle one is okay imo.
![Screenshot 2020-04-17 at 14 56 52](https://user-images.githubusercontent.com/36959754/79571592-bc9f0800-80bb-11ea-8658-6f431e8abfde.png)

Also on 13 inch monitor Woocommerce text overlaps the WordPress icon and it does not look that good.
![Screenshot 2020-04-17 at 14 49 35](https://user-images.githubusercontent.com/36959754/79571087-e277dd00-80ba-11ea-9829-3744279009d4.png)

**Comment by RiccardoMasutti** [comment]
I need help with the alignment of the Wordpress icon
