### ISSUE TITLE
Character encoding problem

### ISSUE THREAD

**Issue by Ruxiol** [btcpayserver/btcpayserver.org#95]
When switched to Bosnian language, some characters are showed in weird way.

i think that's UTF8 encoding problem

As you can see, letters ć/č/ž/đ

![image](https://user-images.githubusercontent.com/12742502/79631891-3981be80-815c-11ea-96c7-7fadf0f4d0be.png)

**Comment by pavlenex** [comment]
@Ruxiol Can you check again, seems to look fine on my end now.
![Screenshot 2020-04-20 at 09 54 10](https://user-images.githubusercontent.com/36959754/79727685-0cb0e100-82ed-11ea-9026-72763e4c38e1.png)

**Comment by dennisreimann** [comment]
That's an issue with the webfont, as the particular font-weights don't include the correct unicode-range for some languages. Let's fix this once the template updates are merged.
